// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	heartbeat "github.com/daniel-oliveiravas/heartbeat-service/business/heartbeat"
	mock "github.com/stretchr/testify/mock"
)

// HeartbeatUsecase is an autogenerated mock type for the HeartbeatUsecase type
type HeartbeatUsecase struct {
	mock.Mock
}

// Beat provides a mock function with given fields: ctx, _a1
func (_m *HeartbeatUsecase) Beat(ctx context.Context, _a1 heartbeat.Heartbeat) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, heartbeat.Heartbeat) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewHeartbeatUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewHeartbeatUsecase creates a new instance of HeartbeatUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHeartbeatUsecase(t mockConstructorTestingTNewHeartbeatUsecase) *HeartbeatUsecase {
	mock := &HeartbeatUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
